name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.0.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  source_gen: ^1.5.0
  flutter_inappwebview_internal_annotations: ^1.1.1

dev_dependencies:
  build_runner: any
  build_test: ^2.2.2
  test: any